'use client';

import { useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'scoutboard-watchlist';
type Player = { id: string; name: string; team: string; position: string; nationality: string };
type Match = { id: string; date: string; time: string; home: string; away: string; team: string; playerIds: string[]; venue: string };

const matches: Match[] = [
  { id:'m1', date:'2026-09-12', time:'16:00', home:'Barcelona', away:'Real Madrid', team:'Barcelona', playerIds:['yamal'], venue:'Estadi Olímpic Lluís Companys' },
  { id:'m2', date:'2026-09-13', time:'20:45', home:'PSG', away:'Marseille', team:'PSG', playerIds:['zaire-emery','doue'], venue:'Parc des Princes' },
  { id:'m3', date:'2026-09-13', time:'16:30', home:'Arsenal', away:'Chelsea', team:'Arsenal', playerIds:['saka'], venue:'Emirates Stadium' },
  { id:'m4', date:'2026-09-14', time:'20:00', home:'Liverpool', away:'Newcastle', team:'Liverpool', playerIds:['wirtz'], venue:'Anfield' },
  { id:'m5', date:'2026-09-14', time:'18:30', home:'Manchester City', away:'Aston Villa', team:'Manchester City', playerIds:['cherki'], venue:'Etihad Stadium' },
];

function makeIcs(playerList: Player[]) {
  const watched = matches.filter((match) => match.playerIds.some((id) => playerList.some((player) => player.id === id)));
  const pad = (value: number) => String(value).padStart(2,'0');
  const dtstamp = new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');
  const escape = (text: string) => text.replace(/([,;\\])/g,'\\$1').replace(/\n/g,'\\n');
  const events = watched.map((match, index) => {
    const [year,month,day] = match.date.split('-').map(Number);
    const [hour,minute] = match.time.split(':').map(Number);
    const start = `${year}${pad(month)}${pad(day)}T${pad(hour)}${pad(minute)}00`;
    const endHour = hour + 2;
    const end = `${year}${pad(month)}${pad(day)}T${pad(endHour)}${pad(minute)}00`;
    const names = match.playerIds.map((id) => playerList.find((player) => player.id === id)?.name).filter(Boolean).join(', ');
    return [
      'BEGIN:VEVENT',
      `UID:${match.id}-scoutboard-${index}@scoutboard`,
      `DTSTAMP:${dtstamp}`,
      `DTSTART:${start}`,
      `DTEND:${end}`,
      `SUMMARY:${escape(`${match.home} vs ${match.away} — Scout ${names}`)}`,
      `LOCATION:${escape(match.venue)}`,
      `DESCRIPTION:${escape(`Players to watch: ${names}. Generated by Scoutboard.`)}`,
      'END:VEVENT',
    ].join('\r\n');
  });
  return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Scoutboard//Scouting Calendar//EN','CALSCALE:GREGORIAN','X-WR-CALNAME:Scoutboard — My Players','X-WR-CALDESC:Matches involving players on your Scoutboard watchlist',...events,'END:VCALENDAR'].join('\r\n');
}

export default function CalendarPage() {
  const [players, setPlayers] = useState<Player[]>([]);
  const [reminder, setReminder] = useState('30 minutes before');
  useEffect(() => { try { const saved = window.localStorage.getItem(STORAGE_KEY); if (saved) setPlayers(JSON.parse(saved)); } catch {} }, []);
  const visible = useMemo(() => matches.filter((match) => match.playerIds.some((id) => players.some((player) => player.id === id))), [players]);

  const downloadIcs = () => {
    const blob = new Blob([makeIcs(players)], { type:'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a'); link.href = url; link.download = 'scoutboard-calendar.ics'; link.click(); URL.revokeObjectURL(url);
  };

  return <main className="workspace">
    <header className="topbar"><a className="brand" href="/">SCOUTBOARD <span>0.1</span></a><nav><a href="/">Board</a><a href="/watchlist">Watchlist <b>{players.length}</b></a><a className="navActive" href="/calendar">Calendar</a></nav></header>
    <section className="calendarHead"><div><div className="eyebrow">MATCH RADAR / SEP 2026</div><h1>My scouting calendar.</h1><p>Only fixtures connected to players you are actually watching appear here.</p></div><div className="calendarActions"><button className="primaryButton" onClick={downloadIcs} disabled={!players.length}>Export .ics</button><button className="ghostButton" onClick={() => alert('On iPhone: Calendar → Calendars → Add Calendar → Add Subscription Calendar, then paste your private Scoutboard feed URL once the server feed is enabled.')}>How iPhone works</button></div></section>
    <section className="calendarLayout">
      <div className="calendarList">{visible.length === 0 ? <article className="emptyCard"><div className="emptyMark">◌</div><h3>Your radar is quiet.</h3><p>Add players to your watchlist and their matching fixtures will appear here automatically.</p><a className="primaryButton" href="/">Add players</a></article> : visible.map((match) => { const watched = match.playerIds.map((id) => players.find((player) => player.id === id)).filter(Boolean) as Player[]; return <article className="matchCard" key={match.id}><div className="matchDate"><strong>{new Date(`${match.date}T12:00:00`).toLocaleDateString('en-GB',{weekday:'short'})}</strong><span>{new Date(`${match.date}T12:00:00`).getDate()}</span></div><div className="matchInfo"><div className="matchTitle"><strong>{match.home}</strong><span>vs</span><strong>{match.away}</strong></div><div className="matchMeta">{match.time} · {match.venue}</div><div className="watcherRow">{watched.map((player) => <span className="watcherPill" key={player.id}>👁 {player.name}</span>)}</div></div><button className="smallButton" onClick={() => alert('Fixture detail is the next build step — this card is already wired around the watched-player relationship.')}>View</button></article>; })}</div>
      <aside className="calendarSide featureCard"><div className="eyebrow">CALENDAR SETTINGS</div><h2>Scouting reminders</h2><p>Export this focused calendar to Apple Calendar. Once the private subscription feed is live, schedule changes can flow through without rebuilding your calendar.</p><label className="fieldLabel">Preferred reminder<select value={reminder} onChange={(event) => setReminder(event.target.value)}><option>30 minutes before</option><option>1 hour before</option><option>2 hours before</option></select></label><div className="calendarSideNote"><span>◎</span><div><strong>{players.length} players</strong><small>{visible.length} upcoming matches in radar</small></div></div><a className="ghostButton" href="/watchlist">Manage players</a></aside>
    </section>
  </main>;
}
