'use client';

import { useEffect, useMemo, useState } from 'react';

type Provider = 'api-football' | 'footballdata' | 'openfoot';
type Player = { id: string; name: string; team: string; teamId: number | string | null; position: string; nationality: string; photo: string | null; provider?: Provider };
type Fixture = { id: string; kickoff: string; timezone: string; venue: string | null; competition: string; home: { id: number | string; name: string; logo?: string | null }; away: { id: number | string; name: string; logo?: string | null }; provider?: Provider };

const STORAGE_KEY = 'scoutboard-watchlist';
const PROVIDER_KEY = 'scoutboard-provider';
const KEY_NAMES: Record<Provider, string> = { footballdata: 'scoutboard-footballdata-key', openfoot: 'scoutboard-openfoot-key', 'api-football': 'scoutboard-api-football-key' };

function getProvider(): Provider { try { const value = window.localStorage.getItem(PROVIDER_KEY) as Provider | null; return value && ['api-football', 'footballdata', 'openfoot'].includes(value) ? value : 'footballdata'; } catch { return 'footballdata'; } }
function getApiKey(provider: Provider) { try { return window.localStorage.getItem(KEY_NAMES[provider]) || ''; } catch { return ''; } }
function readPlayers(): Player[] { try { const raw = window.localStorage.getItem(STORAGE_KEY); return raw ? JSON.parse(raw) : []; } catch { return []; } }
function savePlayers(players: Player[]) { try { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(players)); } catch {} }

function makeIcs(matches: Fixture[], players: Player[]) {
  const pad = (value: number) => String(value).padStart(2, '0');
  const stamp = new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z');
  const escape = (text: string) => text.replace(/([,;\\])/g, '\\$1').replace(/\n/g, '\\n');
  const events = matches.map((match) => {
    const date = new Date(match.kickoff);
    const start = `${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}T${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}00Z`;
    const end = new Date(date.getTime() + 2 * 60 * 60 * 1000);
    const endStamp = `${end.getUTCFullYear()}${pad(end.getUTCMonth() + 1)}${pad(end.getUTCDate())}T${pad(end.getUTCHours())}${pad(end.getUTCMinutes())}00Z`;
    const watchers = players.filter((player) => String(player.teamId) === String(match.home.id) || String(player.teamId) === String(match.away.id)).map((player) => player.name).join(', ');
    return ['BEGIN:VEVENT', `UID:${match.provider || 'scoutboard'}-${match.id}@scoutboard`, `DTSTAMP:${stamp}`, `DTSTART:${start}`, `DTEND:${endStamp}`, `SUMMARY:${escape(`${match.home.name} vs ${match.away.name} — Scout ${watchers}`)}`, `LOCATION:${escape(match.venue || '')}`, `DESCRIPTION:${escape(`Players to watch: ${watchers}. Generated by Scoutboard.`)}`, 'BEGIN:VALARM', 'TRIGGER:-PT30M', 'ACTION:DISPLAY', `DESCRIPTION:${escape(`Scoutboard: ${match.home.name} vs ${match.away.name}`)}`, 'END:VALARM', 'END:VEVENT'].join('\r\n');
  });
  return ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Scoutboard//Scouting Calendar//EN', 'CALSCALE:GREGORIAN', 'X-WR-CALNAME:Scoutboard — My Players', ...events, 'END:VCALENDAR'].join('\r\n');
}

export default function CalendarPage() {
  const [players, setPlayers] = useState<Player[]>([]);
  const [matches, setMatches] = useState<Fixture[]>([]);
  const [loading, setLoading] = useState(false);
  const [hydrating, setHydrating] = useState(false);
  const [error, setError] = useState('');
  const [provider, setProvider] = useState<Provider>('footballdata');

  useEffect(() => {
    setProvider(getProvider());
    setPlayers(readPlayers());
    const sync = () => { setPlayers(readPlayers()); setProvider(getProvider()); };
    window.addEventListener('storage', sync);
    window.addEventListener('focus', sync);
    return () => { window.removeEventListener('storage', sync); window.removeEventListener('focus', sync); };
  }, []);

  useEffect(() => {
    const legacy = players.filter((player) => !player.teamId && player.name);
    if (!legacy.length) return;
    let cancelled = false;
    setHydrating(true);
    Promise.all(legacy.map(async (player) => {
      const p = player.provider || provider;
      const key = getApiKey(p);
      try {
        const response = await fetch(`/api/players/search?q=${encodeURIComponent(player.name)}&provider=${p}`, { headers: key ? { 'x-scoutboard-api-key': key } : undefined });
        const data = await response.json().catch(() => ({}));
        const resolved = (data.players || []).find((candidate: Player) => candidate.teamId);
        return resolved ? { ...player, ...resolved, id: player.id, providerId: player.providerId, provider: p } : player;
      } catch { return player; }
    })).then((resolved) => {
      if (cancelled) return;
      const byId = new Map(resolved.map((player) => [player.id, player]));
      const next = players.map((player) => byId.get(player.id) || player);
      setPlayers(next);
      savePlayers(next);
    }).finally(() => { if (!cancelled) setHydrating(false); });
    return () => { cancelled = true; };
  }, [players.length, provider]);

  useEffect(() => {
    const groups = new Map<Provider, Set<string>>();
    players.forEach((player) => { if (player.teamId) { const p = player.provider || provider; if (!groups.has(p)) groups.set(p, new Set()); groups.get(p)!.add(String(player.teamId)); } });
    if (!groups.size) { setMatches([]); setError(''); return; }
    let cancelled = false;
    setLoading(true); setError('');
    Promise.all([...groups.entries()].flatMap(([p, ids]) => [...ids].map(async (teamId) => {
      const key = getApiKey(p);
      const response = await fetch(`/api/fixtures/team?teamId=${encodeURIComponent(teamId)}&provider=${p}`, { headers: key ? { 'x-scoutboard-api-key': key } : undefined });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data.error || `Fixture request failed (${response.status})`);
      return (data.fixtures || []).map((fixture: Fixture) => ({ ...fixture, provider: p }));
    }))).then((payloads) => {
      if (cancelled) return;
      const merged = payloads.flat().filter(Boolean).sort((a, b) => a.kickoff.localeCompare(b.kickoff));
      setMatches(merged.filter((fixture, index, all) => all.findIndex((item) => `${item.provider}:${item.id}` === `${fixture.provider}:${fixture.id}`) === index));
    }).catch((reason) => { if (!cancelled) { setMatches([]); setError(reason instanceof Error ? reason.message : 'Unable to load fixtures.'); } }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [players, provider]);

  const visible = useMemo(() => matches.filter((match) => players.some((player) => String(player.teamId) === String(match.home.id) || String(player.teamId) === String(match.away.id))), [matches, players]);
  const downloadIcs = () => { const blob = new Blob([makeIcs(visible, players)], { type: 'text/calendar;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'scoutboard-calendar.ics'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 500); };

  return <main className="workspace">
    <header className="topbar"><a className="brand" href="/">SCOUTBOARD <span>0.1</span></a><nav><a href="/">Board</a><a href="/watchlist">Watchlist <b>{players.length}</b></a><a className="navActive" href="/calendar">Calendar</a><a href="/settings">Settings</a></nav></header>
    <section className="calendarHead"><div><div className="eyebrow">MATCH RADAR / LIVE</div><h1>My scouting calendar.</h1><p>Your calendar follows the current clubs of the players you track.</p></div><div className="calendarActions"><button className="primaryButton" onClick={downloadIcs} disabled={!visible.length}>Export .ics</button><a className="ghostButton" href="/watchlist">Manage players</a></div></section>
    <section className="calendarLayout"><div className="calendarList">
      {(loading || hydrating) && <article className="emptyCard"><div className="emptyMark">◌</div><h3>{hydrating ? 'Resolving current clubs…' : 'Building your radar…'}</h3><p>{hydrating ? 'Updating older watchlist entries with their current club identity.' : 'Fetching upcoming fixtures for the clubs you track.'}</p></article>}
      {!loading && !hydrating && error && <article className="emptyCard"><div className="emptyMark">!</div><h3>Fixture provider error.</h3><p>{error}</p><a className="primaryButton" href="/settings">Check provider</a></article>}
      {!loading && !hydrating && !error && !players.length && <article className="emptyCard"><div className="emptyMark">◌</div><h3>Your watchlist is empty.</h3><p>Add a player first. Their current club will drive the fixture radar automatically.</p><a className="primaryButton" href="/">Add a player</a></article>}
      {!loading && !hydrating && !error && players.length > 0 && !visible.length && <article className="emptyCard"><div className="emptyMark">⌁</div><h3>No upcoming fixtures found.</h3><p>Scoutboard has your players, but the active provider returned no scheduled matches for their clubs.</p><a className="ghostButton" href="/settings">Change provider</a></article>}
      {!loading && !hydrating && !error && visible.map((match) => { const date = new Date(match.kickoff); const watched = players.filter((player) => String(player.teamId) === String(match.home.id) || String(player.teamId) === String(match.away.id)); return <article className="matchCard" key={`${match.provider}:${match.id}`}><div className="matchDate"><strong>{date.toLocaleDateString('en-GB', { weekday: 'short' })}</strong><span>{date.getDate()}</span></div><div className="matchInfo"><div className="matchTitle"><strong>{match.home.name}</strong><span>vs</span><strong>{match.away.name}</strong></div><div className="matchMeta">{date.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })} · {match.competition}{match.venue ? ` · ${match.venue}` : ''}</div><div className="watcherRow">{watched.map((player) => <span className="watcherPill" key={`${player.provider}:${player.id}`}>👁 {player.name}</span>)}</div></div><span className="smallButton">{match.provider === 'footballdata' ? 'FD.IO' : match.provider === 'openfoot' ? 'OPENFOOT' : 'API-FB'}</span></article>; })}
    </div><aside className="calendarSide featureCard"><div className="eyebrow">CALENDAR SETTINGS</div><h2>Scouting feed</h2><p>Export only the upcoming matches involving clubs represented in your watchlist. Exported events include a 30-minute alarm.</p><div className="calendarSideNote"><span>◎</span><div><strong>{players.length} tracked player{players.length === 1 ? '' : 's'}</strong><small>{visible.length} upcoming match{visible.length === 1 ? '' : 'es'}</small></div></div><div className="calendarSideNote"><span>◷</span><div><strong>30 min reminder</strong><small>Embedded in exported events</small></div></div><a className="ghostButton" href="/settings">Data provider: {provider === 'footballdata' ? 'Footballdata.io' : provider === 'openfoot' ? 'OpenFootAPI' : 'API-Football'}</a></aside></section>
  </main>;
}
